version: '3'
services:

  zipkin:
    container_name: zipkin-service
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  prometheus:
    container_name: prometheus-service
    image: prom/prometheus
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana-service
    image: grafana/grafana
    ports:
      - "3000:3000"
#global:
#  scrape_interval: 10s
#  evaluation_interval: 10s
#
#scrape_configs:
#  - job_name: "spring-post-service"
#    metrics_path: /actuator/prometheus
#    static_configs:
#      - targets: ['host.docker.internal:8080']
#
#  - job_name: "spring-comment-service"
#    metrics_path: /actuator/prometheus
#    static_configs:
#      - targets: [ 'host.docker.internal:8082' ]